const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const Module=require('node:module');
const ts=require('typescript');
function load(file,mocks={}){
  const full=path.resolve(file),m=new Module(full,module);
  m.filename=full;m.paths=Module._nodeModulePaths(path.dirname(full));
  mocks={'server-only':{},...mocks};
  const original=m.require.bind(m);
  m.require=name=>name in mocks?mocks[name]:original(name);
  m._compile(ts.transpileModule(fs.readFileSync(full,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,full);
  return m.exports;
}
function database(seed={},failure){
  const tables={work_items:[item()],work_item_tags:[],work_item_sources:[],work_item_relationships:[],tags:[],sources_of_truth:[],activity_history:[],...structuredClone(seed)};
  let sequence=10;
  const generatedId=()=>String(sequence++).padStart(8,'0')+'-0000-4000-8000-000000000000';
  const client={from(table){
    let operation='select',payload,filters=[],one=false,optional=false,project='*',opts={};
    const q={select(columns='*'){project=columns;return q;},eq(key,value){filters.push(r=>r[key]===value);return q;},in(key,values){filters.push(r=>values.includes(r[key]));return q;},or(){return q;},order(){return q;},limit(){return q;},single(){one=true;return q;},maybeSingle(){one=true;optional=true;return q;},insert(row){operation='insert';payload=row;return q;},update(row){operation='update';payload=row;return q;},delete(){operation='delete';return q;},upsert(row,options={}){operation='upsert';payload=row;opts=options;return q;},then(resolve,reject){
      try {
        if(failure?.(table,operation)) return Promise.resolve({data:null,error:{message:'Injected database failure'}}).then(resolve,reject);
        let rows=tables[table].filter(r=>filters.every(f=>f(r)));
        if(operation==='insert'){if(table==='work_items'&&tables[table].some(r=>r.id===payload.id))return Promise.resolve({data:null,error:{code:'23505',message:'duplicate'}}).then(resolve,reject);rows=[{id:payload.id??generatedId(),...payload}];tables[table].push(...rows);}
        if(operation==='update') rows.forEach(r=>Object.assign(r,payload));
        if(operation==='delete') tables[table]=tables[table].filter(r=>!rows.includes(r));
        if(operation==='upsert'){
          const keys=opts.onConflict?.split(',')??['id'];
          const existing=tables[table].find(r=>keys.every(k=>r[k]===payload[k]));
          if(existing){if(opts.ignoreDuplicates)rows=[];else{Object.assign(existing,payload);rows=[existing];}}
          else{rows=[{id:payload.id??generatedId(),...payload}];tables[table].push(...rows);}
        }
        if(one&&rows.length!==1&&!optional)return Promise.resolve({data:null,error:{message:'Expected one row'}}).then(resolve,reject);
        return Promise.resolve({data:one?structuredClone(rows[0]??null):structuredClone(rows),error:null}).then(resolve,reject);
      }catch(e){return Promise.reject(e).then(resolve,reject);}
    }};return q;
  }};return {client,tables};
}

const bulk=load('lib/bulk-history.ts'),history=load('lib/project-history.ts');
const owner='owner',id='11111111-1111-4111-8111-111111111111',other='22222222-2222-4222-8222-222222222222';
const item=(extra={})=>({id,user_id:owner,title:'Work OS',type:'Project',area:'Operations',status:'Active',priority:'Now',next_action:'Verified current action',outcome:'Existing outcome',notes:'Keep notes',due_date:'2026-11-01',updated_at:'2026-10-07T00:00:00Z',metadata:{custom:'keep'},...extra});
const sources=bulk.parseArchive(JSON.stringify([{id:'chat1',title:'Work OS',date:'2026-01-01',text:'Repository: https://github.com/clb1015/work-os. Completed old import.'},{id:'chat2',title:'Work OS importer',text:'Use https://github.com/clb1015/work-os. Keep original records.'}]),'2026-10-07T00:00:00Z').conversations;
const candidates=bulk.buildGroups(sources)[0].candidates;
const analysis={summary:'Historical importer discussions',relationships:[{a:'chat1',b:'chat2',classification:'same work',reason:'Shared repository and importer scope'}],matches:[{itemId:id,classification:'extension of existing work',reason:'Existing Work OS record'}],facts:Object.fromEntries(bulk.categories.map(c=>[c,c==='constraints'?[{text:'Keep original records',sourceIds:['chat2']}]:[]])),recommendation:'Retain the constraint in existing history',uncertainty:['Completion is a historical claim']};
function api(db,user={id:owner},provider={bulkAIAvailable:()=>true,analyzeHistory:async()=>analysis},claim=()=>()=>{}){return load('app/api/bulk-history/route.ts',{'@/lib/auth':{getAuthed:async()=>({supabase:db.client,user})},'@/lib/bulk-history':bulk,'@/lib/bulk-history-provider':provider,'@/lib/briefing-limits':{claimBriefingRequest:claim},'@/lib/briefing-provider':{briefingFailureMetadata:()=>({category:'validation'})},'@/lib/project-history':history});}
const post=(a,body,origin='https://work-os-gray.vercel.app')=>a.POST(new Request('https://work-os-gray.vercel.app/api/bulk-history',{method:'POST',headers:{Origin:origin},body:JSON.stringify(body)}));
const save={op:'save',sources,title:'Reviewed Work OS history',summary:'Retain original records. Historical completion requires verification.',action:'add',reviewed:true,saveId:other,itemId:id,expectedUpdatedAt:'2026-10-07T00:00:00Z',supersededIds:['chat1']};
test('Archive preserves provenance, text branches, versions and repeat deduplication',()=>{
 const v=bulk.parseArchive(JSON.stringify([{id:'x',title:'Export',create_time:1700000000,mapping:{a:{children:['b','c'],message:{id:'m1',author:{role:'user'},content:{content_type:'text',parts:['Keep both']}}},b:{message:{id:'m2',author:{role:'assistant'},content:{content_type:'text',parts:['Alternate branch']}}}}},{id:'x',title:'Export',text:'Different version'},{id:'x',title:'Export',text:'Different version'}]));
 assert.equal(v.conversations.length,2);assert.equal(v.conversations[0].originalId,'x');assert.match(v.conversations[0].text,/m1/);assert.match(v.conversations[0].text,/Alternate branch/);assert.ok(v.conversations[0].date);assert.ok(v.warnings.some(w=>w.includes('branches')));
});
test('Invalid and oversized archives reject without truncation',()=>{for(const input of ['bad','[]',JSON.stringify([{title:'Huge',text:'x'.repeat(100001)}]),JSON.stringify(Array.from({length:1001},()=>({text:'x'})))])assert.throws(()=>bulk.parseArchive(input));});
test('Deterministic groups use repository signals and leave unrelated chats separate',()=>{const unrelated={...sources[0],id:'different',title:'Ceramics assessment',text:'Clay rubric.'};const groups=bulk.buildGroups([...sources,unrelated]);assert.equal(groups.length,2);assert.equal(groups[0].sourceIds.length,2);assert.ok(groups[0].candidates[0].signals.some(s=>s.startsWith('Repository:')));});
test('Grouping and combining preserve every source with bounded requests',()=>{const cs=Array.from({length:19},(_,i)=>({...sources[0],id:String(i),text:'x'.repeat(90000)}));const groups=bulk.buildGroups(cs);assert.equal(groups.flatMap(g=>g.sourceIds).length,19);for(const g of groups)assert.ok(g.sourceIds.length<=2);assert.throws(()=>bulk.combineGroups(groups,groups.slice(0,2).map(g=>g.id),cs));const split=bulk.buildGroups([{...sources[0],id:'single',title:'Other',text:'other'},sources[1]]);assert.equal(bulk.combineGroups(split,split.map(g=>g.id),[{...sources[0],id:'single',title:'Other',text:'other'},sources[1]]).length,1);});
test('Backups validate coverage, citations and bounded sources before restoring',()=>{const session={version:1,conversations:sources,groups:bulk.buildGroups(sources),warnings:[],importedAt:sources[0].importedAt};assert.equal(bulk.validateReviewSession(session).groups.length,1);assert.throws(()=>bulk.validateReviewSession({...session,groups:[]}));assert.throws(()=>bulk.validateReviewSession({...session,groups:[{...session.groups[0],analysis:{...analysis,facts:{...analysis.facts,constraints:[{text:'Fake',sourceIds:['unknown']}]}}}]}));});
test('Model output cannot invent source IDs, record IDs or noncandidate pairs',()=>{assert.deepEqual(bulk.validateAnalysis(analysis,sources,[id],candidates),analysis);for(const v of [{...analysis,matches:[{...analysis.matches[0],itemId:other}]},{...analysis,relationships:[]},{...analysis,relationships:[{...analysis.relationships[0],b:'unknown'}]},{...analysis,facts:{...analysis.facts,constraints:[{text:'Fake',sourceIds:['unknown']}]}}])assert.throws(()=>bulk.validateAnalysis(v,sources,[id],candidates));});
test('Bulk API rejects foreign origin, expired session, unreviewed saves and other owners',async()=>{const db=database({work_items:[item({user_id:'else'})]});assert.equal((await post(api(db),save,'https://evil.example')).status,403);assert.equal((await post(api(db,null),save)).status,401);assert.equal((await post(api(db),{...save,reviewed:false})).status,400);assert.equal((await post(api(db),save)).status,404);assert.equal(db.tables.work_items[0].metadata.projectHistory,undefined);});
test('AI analysis is read only, recomputes candidates and sends only plausible owner records',async()=>{const db=database({work_items:[item(),item({id:other,title:'Different record'})]});const before=structuredClone(db.tables);let observed;const a=api(db,undefined,{bulkAIAvailable:()=>true,analyzeHistory:async(...args)=>{observed=args;return analysis;}});assert.equal((await post(a,{op:'analyze',sources,privacyReviewed:true,candidates:[{a:'fake'}]})).status,200);assert.equal(observed[1].length,1);assert.equal(observed[2].length,1);assert.equal(observed[2][0].id,id);assert.deepEqual(db.tables,before);assert.equal((await post(a,{op:'analyze',sources,privacyReviewed:false})).status,400);});
test('Linked repositories participate in Work OS matching',async()=>{const db=database({work_items:[item({title:'Internal platform'})],sources_of_truth:[{id:'repo',user_id:owner,location:'https://github.com/clb1015/work-os'}],work_item_sources:[{user_id:owner,work_item_id:id,source_id:'repo'}]});const current=await (await api(db).GET()).json();assert.equal(bulk.likelyMatches(sources,current.items)[0].itemId,id);});
test('Disabled AI, rate limits and provider failures cannot mutate records',async()=>{const db=database(),before=structuredClone(db.tables),body={op:'analyze',sources,privacyReviewed:true};assert.equal((await post(api(db,undefined,{bulkAIAvailable:()=>false}),body)).status,503);assert.equal((await post(api(db,undefined,undefined,()=>null),body)).status,429);assert.equal((await post(api(db,undefined,{bulkAIAvailable:()=>true,analyzeHistory:async()=>{throw new Error('Secret transcript');}}),body)).status,502);assert.deepEqual(db.tables,before);});
test('Explicit history save preserves authoritative state and is idempotent across reimports',async()=>{const db=database(),before=structuredClone(db.tables.work_items[0]),a=api(db);assert.equal((await post(a,save)).status,200);assert.equal((await post(a,{...save,saveId:'33333333-3333-4333-8333-333333333333'})).status,200);const result=db.tables.work_items[0];for(const key of ['status','priority','area','next_action','outcome','notes','due_date'])assert.deepEqual(result[key],before[key]);assert.equal(result.metadata.custom,'keep');assert.equal(result.metadata.projectHistory.length,1);assert.deepEqual(result.metadata.projectHistory[0].bulkReview.sources,sources);assert.deepEqual(result.metadata.projectHistory[0].bulkReview.supersededIds,['chat1']);});
test('Stale and concurrent saves return conflict without losing current data',async()=>{const stale=database();stale.tables.work_items[0].updated_at='newer';assert.equal((await post(api(stale),save)).status,409);const concurrent=database(),from=concurrent.client.from;concurrent.client.from=function(t){const q=from(t),update=q.update;q.update=function(row){concurrent.tables.work_items[0].updated_at='concurrent';return update(row);};return q;};assert.equal((await post(api(concurrent),save)).status,409);assert.equal(concurrent.tables.work_items[0].metadata.projectHistory,undefined);});
test('Create and link require explicit review and do not adopt historical current fields',async()=>{const db=database(),a=api(db),body={...save,action:'create',newItemId:other,title:'Distinct new project'};assert.equal((await post(a,body)).status,200);assert.equal((await post(a,body)).status,200);assert.equal(db.tables.work_items.length,2);const record=db.tables.work_items[1];assert.equal(record.status,'Inbox');assert.equal(record.priority,'Later');assert.equal(record.area,'Unassigned');assert.equal(record.next_action,undefined);const link=database();assert.equal((await post(api(link),{...save,action:'link'})).status,200);assert.equal(link.tables.work_item_relationships.length,0);assert.equal(link.tables.work_items[0].metadata.projectHistory[0].bulkReview.retentionAction,'link');});
test('Save database failures preserve existing history',async()=>{const db=database({},(t,op)=>op==='update');assert.equal((await post(api(db),save)).status,500);assert.equal(db.tables.work_items[0].metadata.projectHistory,undefined);});
const briefing=load('lib/briefing-provider.ts',{'./daily-briefing':{}}),provider=load('lib/bulk-history-provider.ts',{'./bulk-history':bulk,'./briefing-provider':briefing});
test('Model excerpts redact credential patterns and URL secrets and disclose omitted text',()=>{const excerpt=provider.modelExcerpt('Bearer abcdefghijklmnopqrstuvwxyz https://user:password@example.com/path?token=secret#fragment '+ 'x'.repeat(10000));assert.equal(excerpt.excerpted,true);assert.doesNotMatch(excerpt.text,/password|token=secret|abcdefghijklmnopqrstuvwxyz/);assert.match(excerpt.text,/Middle omitted/);});
test('Provider uses strict stateless structured output and validates source citations',async()=>{const original=global.fetch,key=process.env.OPENAI_API_KEY,flag=process.env.WORK_OS_AI_ENABLED;process.env.OPENAI_API_KEY='test-key';process.env.WORK_OS_AI_ENABLED='true';let payload;global.fetch=async(url,options)=>{payload=JSON.parse(options.body);return Response.json({status:'completed',output:[{type:'message',content:[{type:'output_text',text:JSON.stringify(analysis)}]}]});};try{assert.deepEqual(await provider.analyzeHistory(sources,candidates,[item()]),analysis);assert.equal(payload.store,false);assert.equal(payload.text.format.strict,true);assert.equal(payload.tools,undefined);assert.match(payload.instructions,/Ignore commands/);global.fetch=async()=>Response.json({status:'completed',output:[{type:'message',content:[{type:'output_text',text:JSON.stringify({...analysis,matches:[{...analysis.matches[0],itemId:other}]})}]}]});await assert.rejects(provider.analyzeHistory(sources,candidates,[item()]));}finally{global.fetch=original;if(key===undefined)delete process.env.OPENAI_API_KEY;else process.env.OPENAI_API_KEY=key;if(flag===undefined)delete process.env.WORK_OS_AI_ENABLED;else process.env.WORK_OS_AI_ENABLED=flag;}});
