'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {parseArchive,buildGroups,combineGroups,extractSignals,likelyMatches,analysisSummary,categories,validateReviewSession,type ReviewSession,type ReviewGroup,type Conversation,type Analysis} from '@/lib/bulk-history';
import {loadReview,storeReview} from '@/lib/bulk-history-storage';
type CurrentItem={id:string;title:string;type:string;area:string;status:string;priority:string;next_action:string|null;outcome:string|null;source_url?:string|null;updated_at:string};
const categoryLabels:Record<typeof categories[number],string>={decisions:'Important decisions',completed:'Completed work claimed in chats',research:'Useful research or facts to verify',constraints:'Established constraints',questions:'Unresolved questions',nextSteps:'Historical next steps',superseded:'Likely superseded information'};
async function request(body?:Record<string,unknown>){const r=await fetch('/api/bulk-history',body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{cache:'no-store'});if(r.status===401){window.location.assign('/login?error=session-expired');throw new Error('Sign in again.');}const p=await r.json();if(!r.ok)throw new Error(p.error||'Review request failed.');return p;}
export default function BulkHistoryReview({owner,onSaved,onOpen}:{owner:string;onSaved:()=>void;onOpen:(id:string)=>void}){
  const [session,setSession]=useState<ReviewSession|null>(null),[ready,setReady]=useState(false),[items,setItems]=useState<CurrentItem[]>([]),[aiAvailable,setAIAvailable]=useState(false);
  const [active,setActive]=useState(''),[filter,setFilter]=useState('pending'),[query,setQuery]=useState(''),[selected,setSelected]=useState<string[]>([]);
  const [error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[replace,setReplace]=useState(false),[privacy,setPrivacy]=useState(false),[reviewed,setReviewed]=useState(false);
  const [action,setAction]=useState('add'),[target,setTarget]=useState(''),[title,setTitle]=useState(''),[summary,setSummary]=useState('');
  const pending=useRef(false),writeQueue=useRef(Promise.resolve());
  const group=session?.groups.find(g=>g.id===active);
  const sources=useMemo(()=>session?.conversations.filter(c=>group?.sourceIds.includes(c.id))||[],[session,group]);
  const matches=useMemo(()=>likelyMatches(sources,items),[sources,items]);
  useEffect(()=>{let cancelled=false;loadReview(owner).then(s=>{if(!cancelled)setSession(s?validateReviewSession(s):null);}).catch(e=>{if(!cancelled)setError(e.message);}).finally(()=>{if(!cancelled)setReady(true);});request().then(p=>{if(!cancelled){setItems(p.items);setAIAvailable(p.aiAvailable);}}).catch(e=>{if(!cancelled)setError(e.message);});return()=>{cancelled=true;};},[owner]);
  useEffect(()=>{if(!ready||!session)return;writeQueue.current=writeQueue.current.catch(()=>{}).then(()=>storeReview(owner,session)).catch(e=>setError(e.message));},[session,ready,owner]);
  function patch(id:string,value:Partial<ReviewGroup>){setSession(s=>s?{...s,groups:s.groups.map(g=>g.id===id?{...g,...value}:g)}:s);setReviewed(false);}
  function choose(g:ReviewGroup){setActive(g.id);setTitle(g.editedTitle??g.title);setSummary(g.editedSummary||(g.analysis?analysisSummary(g.analysis):''));setTarget('');setReviewed(false);setPrivacy(false);setAction('add');setError('');setMessage('');}
  async function run(fn:()=>Promise<void>){if(pending.current)return;pending.current=true;setBusy(true);setError('');setMessage('');try{await fn();}catch(e){setError(e instanceof Error?e.message:'Please retry.');}finally{pending.current=false;setBusy(false);}}
  async function importFile(file:File){await run(async()=>{if(session&&!replace)throw new Error('Export your current review and confirm replacement before importing a different archive.');if(file.size>50000000||!file.name.toLowerCase().endsWith('.json'))throw new Error('Choose conversations.json under 50 MB. Extract ZIP files first.');const raw=await file.text();let parsed;try{parsed=JSON.parse(raw);}catch{throw new Error('Invalid JSON archive.');}
    // Backups retain review state as well as sources; validate structural bounds before restoring.
    let next:ReviewSession;
    if(parsed.version===1&&Array.isArray(parsed.groups)&&Array.isArray(parsed.conversations)){
      next=validateReviewSession(parsed);
    }else{const {conversations,warnings}=parseArchive(raw);next={version:1,conversations,groups:buildGroups(conversations),warnings,importedAt:new Date().toISOString()};}
    await writeQueue.current;await storeReview(owner,next);setSession(next);setActive('');setSelected([]);setReplace(false);setMessage(`${next.conversations.length} conversations imported into ${next.groups.length} review groups. No Work Items changed.`);
  });}
  function exportBackup(){if(!session)return;const url=URL.createObjectURL(new Blob([JSON.stringify(session,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='work-os-history-review.json';a.click();URL.revokeObjectURL(url);}
  function split(sourceId:string){if(!session||!group||sources.length<2)return;const source=sources.find(s=>s.id===sourceId)!;const remainder=group.sourceIds.filter(id=>id!==sourceId);const fresh:ReviewGroup={...buildGroups([source])[0],manual:true};setSession({...session,groups:[...session.groups.filter(g=>g.id!==group.id),{...group,sourceIds:remainder,candidates:group.candidates.filter(c=>c.a!==sourceId&&c.b!==sourceId),analysis:undefined,editedSummary:undefined,saveId:crypto.randomUUID(),supersededIds:group.supersededIds.filter(id=>id!==sourceId)},fresh]});setActive('');setSelected([]);setReviewed(false);}
  const visible=(session?.groups||[]).filter(g=>(filter==='all'||g.state===filter)&&(!query.trim()||[g.title,...(session?.conversations.filter(c=>g.sourceIds.includes(c.id)).map(c=>c.title)||[])].join(' ').toLowerCase().includes(query.toLowerCase())));
  return <div className="bulk-review"><div className="page-heading"><div><h1>Bulk chat history review</h1><p>Import → Analyze → Group → Compare → Recommend → Human Review → Save</p></div></div>
    <section className="history-panel"><h2>Import your supplied archive</h2><p>Choose the extracted conversations.json file, a conversation array, or a saved review backup. No automatic chat collection. Archives stay in this browser until you request AI analysis or save reviewed history.</p><p>Remove identifiable student information and secrets first. Browser storage is specific to this device and site; export a backup to keep a durable copy.</p>
      {!ready?<p role="status">Restoring your local review…</p>:<><label>JSON archive<input type="file" accept=".json" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)void importFile(file);e.target.value='';}}/></label>{session&&<><button onClick={exportBackup} disabled={busy}>Export review backup</button><label className="history-check"><input type="checkbox" checked={replace} disabled={busy} onChange={e=>setReplace(e.target.checked)}/>Replace the local review when I import another archive. Existing Work OS history is unaffected.</label></>}</>}
      {error&&<p className="data-state error" role="alert">{error}</p>}{message&&<p role="status">{message}</p>}{!!session?.warnings.length&&<details><summary>{session.warnings.length} import notices</summary><ul>{session.warnings.map((w,i)=><li key={i}>{w}</li>)}</ul></details>}
    </section>
    {session&&<><div className="bulk-toolbar"><label>Find groups<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Project or chat title"/></label><label>Review state<select value={filter} onChange={e=>setFilter(e.target.value)}>{['pending','later','ignored','saved','all'].map(s=><option key={s}>{s}</option>)}</select></label><button disabled={busy||selected.length<2} onClick={()=>{try{setSession({...session,groups:combineGroups(session.groups,selected,session.conversations)});setSelected([]);setActive('');}catch(e){setError((e as Error).message);}}}>Combine selected groups</button><button disabled={busy} onClick={()=>void run(async()=>{const p=await request();setItems(p.items);setAIAvailable(p.aiAvailable);setReviewed(false);setMessage('Current Work OS state refreshed. Review the selected action again.');})}>Refresh Work OS records</button></div>
    <p>{session.conversations.length} source conversations · {session.groups.length} groups · {session.groups.filter(g=>g.state==='pending').length} awaiting review. Candidate groups are suggestions, not confirmed duplicates.</p>
    <div className="bulk-layout"><section className="bulk-groups" aria-label="Related chat groups">{!visible.length&&<p>No groups in this filter.</p>}{visible.map(g=><article className={active===g.id?'bulk-card selected':'bulk-card'} key={g.id}><label className="history-check"><input type="checkbox" disabled={busy||g.state==='saved'} checked={selected.includes(g.id)} onChange={e=>setSelected(e.target.checked?[...selected,g.id]:selected.filter(id=>id!==g.id))}/>Select to combine</label><button className="bulk-group-title" disabled={busy} onClick={()=>choose(g)}>{g.title}</button><p>{g.sourceIds.length} chats · {g.state} · {g.analysis?'AI reviewed':'Deterministic candidates'}</p><p>{likelyMatches(session.conversations.filter(c=>g.sourceIds.includes(c.id)),items).length} likely Work OS matches</p>{g.analysis&&<p>{g.analysis.recommendation}</p>}<ul>{session.conversations.filter(c=>g.sourceIds.includes(c.id)).map(c=><li key={c.id}>{c.title} · {c.date?.slice(0,10)||'Unknown date'}</li>)}</ul></article>)}</section>
    <section className="history-panel bulk-detail" aria-label="Selected group review">{!group?<p>Select a group to compare its chats with current Work OS records.</p>:<>
      <h2>{group.title}</h2><p className="bulk-historical">Historical source material. This is not current Work OS state.</p>
      <h3>Source conversations</h3>{sources.map(c=><details key={c.id}><summary>{c.title} · {c.date?.slice(0,10)||'Unknown date'}</summary><p>Original ID: {c.originalId||'Not supplied'}<br/>Imported: {c.importedAt}</p><pre>{c.text}</pre>{group.state!=='saved'&&<><label className="history-check"><input type="checkbox" checked={group.supersededIds.includes(c.id)} disabled={busy} onChange={e=>patch(group.id,{supersededIds:e.target.checked?[...group.supersededIds,c.id]:group.supersededIds.filter(id=>id!==c.id)})}/>Mark this source as superseded in the saved review</label><button disabled={busy||sources.length<2} onClick={()=>split(c.id)}>Keep this chat as a separate group</button></>}</details>)}
      <details><summary>Deterministic candidate signals</summary>{group.candidates.length?group.candidates.map((c,i)=><p key={i}>{sources.find(s=>s.id===c.a)?.title} ↔ {sources.find(s=>s.id===c.b)?.title}: {c.signals.join('; ')}</p>):<p>No pair met the deterministic threshold. You can inspect this source independently or combine groups manually.</p>}</details>
      <h3>Current Work OS comparison</h3><p>Likely title / URL / repository matches. These are clues, not automatic merges.</p>{!matches.length&&<p>No deterministic match. You can still select any existing record below.</p>}{items.filter(i=>matches.some(m=>m.itemId===i.id)).map(i=><article className="bulk-current" key={i.id}><button disabled={busy} onClick={()=>onOpen(i.id)}>{i.title}</button><p>Current status: {i.status} · Priority: {i.priority}<br/>Current next action: {i.next_action||'Not recorded'}<br/>Outcome: {i.outcome||'Not recorded'}</p><small>{matches.find(m=>m.itemId===i.id)?.reasons.join('; ')}</small></article>)}
      {group.state!=='saved'&&<><label className="history-check"><input disabled={busy} type="checkbox" checked={privacy} onChange={e=>setPrivacy(e.target.checked)}/>I removed student identifiers and secrets from these sources. Send bounded excerpts and current candidate summaries to OpenAI for analysis.</label><p>Up to eight chats per request; long chats use their first and last 2,500 characters. Full source text remains available above. AI does not inspect omitted text or linked files.</p><button className="primary" disabled={busy||!privacy||!aiAvailable} onClick={()=>void run(async()=>{const p=await request({op:'analyze',sources,privacyReviewed:true});patch(group.id,{analysis:p.analysis,editedSummary:undefined});setSummary(analysisSummary(p.analysis));setMessage('AI analysis ready for your review. Work OS records are unchanged.');})}>{busy?'Working…':group.analysis?'Re-analyze group':'Analyze this group with AI'}</button>{!aiAvailable&&<p>AI is disabled in this environment. Review and save manually, or enable it through the existing production AI settings.</p>}</>}
      {group.analysis&&<AnalysisView analysis={group.analysis} sources={sources} items={items}/>}
      {group.state==='saved'?<p role="status">Saved to {items.find(i=>i.id===group.savedItemId)?.title||'Work OS'}. Original chats remain intact.</p>:<>
        <h3>Human review and save</h3><label>History / new project title<input disabled={busy} value={title} maxLength={300} onChange={e=>{setTitle(e.target.value);patch(group.id,{editedTitle:e.target.value});}}/></label><label>Reviewed historical summary<textarea disabled={busy} rows={10} maxLength={30000} value={summary} onChange={e=>{setSummary(e.target.value);patch(group.id,{editedSummary:e.target.value});}}/></label>
        <label>Save action<select disabled={busy} value={action} onChange={e=>{setAction(e.target.value);setReviewed(false);}}><option value="add">Add to existing Work Item history</option><option value="create">Create a new Work Item</option><option value="link">Link this historical group to a related Work Item</option></select></label>
        {action!=='create'?<label>Destination Work Item<select disabled={busy} value={target} onChange={e=>{setTarget(e.target.value);setReviewed(false);}}><option value="">Choose a record</option>{items.map(i=><option key={i.id} value={i.id}>{i.title} ({i.status})</option>)}</select></label>:<p>A new Project will be created as Inbox / Later / Unassigned with this reviewed history. Historical status, dates and next steps will not be copied into current fields.</p>}
        {action==='link'&&<p>This adds a related-history reference to the selected record. It does not merge Work Items or create a blocking relationship.</p>}
        {target&&<p className="bulk-current">Current destination: {items.find(i=>i.id===target)?.title} · {items.find(i=>i.id===target)?.status} / {items.find(i=>i.id===target)?.priority}<br/>Next action: {items.find(i=>i.id===target)?.next_action||'Not recorded'}</p>}
        <label className="history-check"><input type="checkbox" disabled={busy} checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>I reviewed the source texts, historical summary, superseded markers and exact save action. Preserve original source text with this history.</label>
        <button className="primary" disabled={busy||!reviewed||!summary.trim()||!title.trim()||(action!=='create'&&!target)} onClick={()=>void run(async()=>{const p=await request({op:'save',sources,title,summary,action,reviewed:true,saveId:group.saveId,newItemId:group.saveId,itemId:target,expectedUpdatedAt:items.find(i=>i.id===target)?.updated_at,supersededIds:group.supersededIds});patch(group.id,{state:'saved',savedItemId:p.itemId,editedSummary:summary});onSaved();const fresh=await request();setItems(fresh.items);setMessage(p.duplicate?'This group was already saved; no duplicate history added.':'Reviewed history saved.');})}>{busy?'Working…':action==='create'?'Create reviewed Work Item':'Save reviewed history'}</button>
        <div className="modal-actions"><button disabled={busy} onClick={()=>patch(group.id,{state:'later'})}>Review later</button><button disabled={busy} onClick={()=>patch(group.id,{state:'ignored'})}>Ignore group</button>{group.state!=='pending'&&<button disabled={busy} onClick={()=>patch(group.id,{state:'pending'})}>Return to pending</button>}</div><p>Ignore and Review later change only this local queue. They do not archive or delete conversations or Work Items.</p>
      </>}
    </>}</section></div></>}
  </div>;
}
function AnalysisView({analysis,sources,items}:{analysis:Analysis;sources:Conversation[];items:CurrentItem[]}){
  return <div className="bulk-analysis"><h3>AI synthesis for review</h3><p>{analysis.summary}</p><h4>Relationship judgments</h4><ul>{analysis.relationships.map((r,i)=><li key={i}>{sources.find(s=>s.id===r.a)?.title} ↔ {sources.find(s=>s.id===r.b)?.title}: <strong>{r.classification}</strong>. {r.reason}</li>)}</ul><h4>Work OS match judgments</h4><ul>{analysis.matches.map(m=><li key={m.itemId}>{items.find(i=>i.id===m.itemId)?.title}: <strong>{m.classification}</strong>. {m.reason}</li>)}</ul>{categories.map(k=><div key={k}><h4>{categoryLabels[k]}</h4>{analysis.facts[k].length?<ul>{analysis.facts[k].map((f,i)=><li key={i}>{f.text}<small>Sources: {f.sourceIds.map(id=>sources.find(s=>s.id===id)?.title).join('; ')}</small></li>)}</ul>:<p>Not established by the supplied excerpts.</p>}</div>)}<h4>Retention recommendation</h4><p>{analysis.recommendation}</p><h4>Uncertainty</h4><ul>{analysis.uncertainty.map((u,i)=><li key={i}>{u}</li>)}</ul></div>;
}
