export const AREAS = [
  "Curriculum", "Finance & Budget", "Advocacy", "Construction / FF&E", "Technology",
  "Data / Analytics", "Teacher Support / PD", "CTE Development", "Presentations / Communications",
  "Partnerships / Grants",
] as const;
export const STATUSES = ["Inbox", "Clarify", "Ready", "Active", "Waiting", "Review", "Done", "Archived"] as const;
export const TYPES = ["Project", "Idea", "Workflow", "Dashboard", "Tool / App", "Resource", "Decision", "Issue", "Presentation"] as const;
export const PRIORITIES = ["Now", "Next", "Later", "Someday"] as const;
export const IMPACTS = ["Low", "Medium", "High"] as const;
export const EFFORTS = ["Quick", "Moderate", "Significant"] as const;
export const IDEA_STAGES = ["Spark", "Explore", "Promising", "Park"] as const;

export type Area = (typeof AREAS)[number];
export type WorkStatus = (typeof STATUSES)[number];
export type WorkType = (typeof TYPES)[number];
export type Priority = (typeof PRIORITIES)[number];
export type Impact = (typeof IMPACTS)[number];
export type Effort = (typeof EFFORTS)[number];
export type IdeaStage = (typeof IDEA_STAGES)[number];

export interface WorkflowStep { title: string; done?: boolean; current?: boolean }
export interface WorkItem {
  id: string; title: string; type: WorkType; area: Area; status: WorkStatus; priority: Priority;
  impact: Impact; effort: Effort; outcome: string; next_action: string; why_now: string;
  waiting_on: string; target_date: string; source_of_truth: string; related_items: string[];
  tags: string[]; notes: string; created_at: string; last_activity_at: string; completed_at: string;
  idea_stage?: IdeaStage; workflow_run?: string; workflow_steps?: WorkflowStep[]; replaced_by?: string;
}

const base = {
  priority: "Next" as Priority, impact: "Medium" as Impact, effort: "Moderate" as Effort,
  why_now: "", waiting_on: "", target_date: "", source_of_truth: "Work OS",
  related_items: [], tags: [], notes: "", created_at: "2026-07-18", last_activity_at: "2026-09-29", completed_at: "",
};

export const initialWorkItems: WorkItem[] = [
  { ...base, id:"intelligence-hub", title:"District Arts Intelligence Hub", type:"Dashboard", area:"Data / Analytics", status:"Active", priority:"Now", impact:"High", effort:"Significant", outcome:"Early-warning system identifying arts programs needing district support.", next_action:"Finalize enrollment warning indicators", why_now:"Fall enrollment changes need district visibility before staffing decisions.", target_date:"2026-10-09", source_of_truth:"clb1015/district-arts-dashboard", related_items:["enrollment-dashboard","arts-import","data-debrief"], tags:["enrollment","early-warning"], notes:"Combine staffing, enrollment, and program health indicators.", created_at:"2026-03-04", last_activity_at:"2026-10-01", completed_at:"" },
  { ...base, id:"arts-import", title:"Arts Import & Reconciliation", type:"Tool / App", area:"Technology", status:"Review", priority:"Now", impact:"High", effort:"Significant", outcome:"Reliable browser-based import and reconciliation for district arts records.", next_action:"Complete browser acceptance testing", target_date:"2026-10-07", source_of_truth:"clb1015/district-arts-dashboard", related_items:["intelligence-hub","enrollment-dashboard"], tags:["enrollment","importer","data-quality"], last_activity_at:"2026-10-01" },
  { ...base, id:"enrollment-dashboard", title:"Enrollment Dashboard", type:"Dashboard", area:"Data / Analytics", status:"Active", priority:"Now", impact:"High", effort:"Moderate", outcome:"Trusted view of arts enrollment by school, course, and program.", next_action:"Validate 2026 enrollment course mappings", target_date:"2026-10-06", source_of_truth:"Power BI / Arts Enrollment", related_items:["intelligence-hub","arts-import"], tags:["enrollment","courses"], last_activity_at:"2026-09-30" },
  { ...base, id:"genmusbot", title:"GenMusBot", type:"Tool / App", area:"Technology", status:"Active", priority:"Later", impact:"Medium", effort:"Significant", outcome:"Help general music teachers quickly find standards-aligned lesson support.", next_action:"Review fall pilot feedback", source_of_truth:"clb1015/genmusbot", tags:["teacher-support"], last_activity_at:"2026-09-19" },
  { ...base, id:"ai-fellows", title:"AI Fellows Problem of Practice", type:"Project", area:"Teacher Support / PD", status:"Active", priority:"Next", impact:"High", effort:"Moderate", outcome:"A tested problem-of-practice model for responsible instructional AI use.", next_action:"Synthesize cohort observations", target_date:"2026-10-18", source_of_truth:"AI Fellows shared drive", tags:["AI","professional-learning"], last_activity_at:"2026-09-28" },
  { ...base, id:"band-funding", title:"Band Central Funding", type:"Workflow", area:"Finance & Budget", status:"Active", priority:"Now", impact:"High", effort:"Significant", outcome:"Eligible schools receive equitable, documented instrument funding.", next_action:"Collect three quotes from participating schools", why_now:"Current purchasing window closes in November.", source_of_truth:"Band Central Funding workbook", workflow_run:"2026–27", workflow_steps:[{title:"Identify eligible schools",done:true},{title:"Notify directors",done:true},{title:"Collect three quotes",current:true},{title:"Validate purchases"},{title:"Transfer funds"},{title:"Purchase"},{title:"Archive"}], related_items:["equipment-cycle"], tags:["funding","instruments"], last_activity_at:"2026-09-30" },
  { ...base, id:"valencia", title:"Valencia DirectConnect Alignment", type:"Project", area:"CTE Development", status:"Active", priority:"Next", impact:"High", effort:"Significant", outcome:"Align district arts pathways with Valencia DirectConnect opportunities.", next_action:"", why_now:"Program sequence decisions are due this semester.", source_of_truth:"CTE pathway planning folder", tags:["pathways","higher-ed"], last_activity_at:"2026-09-23" },
  { ...base, id:"ffe-lessons", title:"FF&E Lessons Learned", type:"Workflow", area:"Construction / FF&E", status:"Active", priority:"Next", impact:"Medium", effort:"Moderate", outcome:"Apply consistent arts-space lessons to every capital project.", next_action:"Add Horizon West post-occupancy findings", source_of_truth:"Capital projects knowledge base", tags:["facilities"], last_activity_at:"2026-09-21" },
  { ...base, id:"nova-stage", title:"Nova Lakes Stage Issue", type:"Issue", area:"Construction / FF&E", status:"Waiting", priority:"Now", impact:"High", effort:"Moderate", outcome:"Restore a safe, instruction-ready stage at Nova Lakes.", next_action:"Review facilities response when received", waiting_on:"Facilities / Construction response", target_date:"2026-10-10", source_of_truth:"Facilities ticket FC-2841", tags:["stage","safety"], last_activity_at:"2026-09-24" },
  { ...base, id:"seal", title:"Florida Seal of Fine Arts", type:"Workflow", area:"Curriculum", status:"Active", priority:"Now", impact:"High", effort:"Moderate", outcome:"Eligible students receive consistent guidance and recognition.", next_action:"Publish school coordinator checklist", target_date:"2026-10-14", source_of_truth:"Seal implementation guide", tags:["recognition"], last_activity_at:"2026-09-27" },
  { ...base, id:"chorus", title:"All County Elementary Chorus", type:"Project", area:"Curriculum", status:"Active", priority:"Next", impact:"Medium", effort:"Significant", outcome:"Deliver an equitable, high-quality county elementary chorus experience.", next_action:"Confirm repertoire and clinician schedule", target_date:"2026-10-22", source_of_truth:"All County planning folder", tags:["event","elementary"], last_activity_at:"2026-09-29" },
  { ...base, id:"disney-transport", title:"Disney Musicals transportation", type:"Issue", area:"Partnerships / Grants", status:"Waiting", priority:"Now", impact:"Medium", effort:"Quick", outcome:"Confirm transportation access for participating schools.", next_action:"Confirm bus allocation after partner reply", waiting_on:"Transportation Services", source_of_truth:"Email thread: Disney Musicals transportation", tags:["transportation"], last_activity_at:"2026-09-26" },
  { ...base, id:"chart-builder", title:"Modern Band Chart Builder", type:"Tool / App", area:"Technology", status:"Review", priority:"Next", impact:"Medium", effort:"Significant", outcome:"Let teachers prepare accessible modern-band charts efficiently.", next_action:"Run accessibility review", source_of_truth:"clb1015/modern-band-chart-builder", tags:["modern-band"], last_activity_at:"2026-09-24" },
  { ...base, id:"mcgolden", title:"McGolden / Osceola Rocks grant", type:"Project", area:"Partnerships / Grants", status:"Active", priority:"Next", impact:"High", effort:"Moderate", outcome:"Secure sustainable support for student modern-band experiences.", next_action:"Finalize partner budget narrative", target_date:"2026-10-15", source_of_truth:"Grant workspace / Osceola Rocks", tags:["grant","modern-band"], last_activity_at:"2026-09-30" },
  { ...base, id:"data-debrief", title:"Data Debrief Dashboard", type:"Dashboard", area:"Data / Analytics", status:"Review", priority:"Later", impact:"Medium", effort:"Moderate", outcome:"Give school leaders a repeatable view for program data conversations.", next_action:"Validate principal-facing labels", source_of_truth:"Power BI / Data Debrief", related_items:["enrollment-dashboard","intelligence-hub"], tags:["enrollment","leadership"], last_activity_at:"2026-09-22" },
  { ...base, id:"equipment-cycle", title:"Arts Equipment Replacement Cycle", type:"Idea", area:"Finance & Budget", status:"Inbox", priority:"Later", impact:"High", effort:"Significant", outcome:"", next_action:"Clarify available inventory and lifecycle data", source_of_truth:"Work OS", related_items:["band-funding"], tags:["equipment","planning"], idea_stage:"Spark", last_activity_at:"2026-09-30" },
  { ...base, id:"instrument-inventory", title:"Instrument Inventory", type:"Resource", area:"Finance & Budget", status:"Ready", priority:"Next", impact:"High", effort:"Moderate", outcome:"A dependable school-level inventory for planning purchases and replacement.", next_action:"Reconcile 12 unmatched school records", source_of_truth:"District instrument inventory workbook", tags:["equipment","inventory"], last_activity_at:"2026-09-28" },
  { ...base, id:"ffe-planning", title:"FF&E Equipment Planning", type:"Workflow", area:"Construction / FF&E", status:"Ready", priority:"Later", impact:"High", effort:"Significant", outcome:"Consistent equipment planning for new and renovated arts spaces.", next_action:"Review standard package assumptions", source_of_truth:"FF&E standards workbook", tags:["equipment","facilities"], last_activity_at:"2026-09-20" },
  { ...base, id:"advocacy-brief", title:"2025–26 Arts Impact Brief", type:"Presentation", area:"Advocacy", status:"Done", priority:"Later", impact:"High", effort:"Moderate", outcome:"Communicate district arts reach and results to cabinet and community partners.", next_action:"", source_of_truth:"Communications archive / Arts Impact Brief", tags:["annual-review"], last_activity_at:"2026-08-14", completed_at:"2026-08-14" },
  { ...base, id:"summer-pd", title:"Summer Arts Leadership Institute", type:"Project", area:"Teacher Support / PD", status:"Done", priority:"Later", impact:"High", effort:"Significant", outcome:"Deliver aligned leadership learning for school arts teams.", next_action:"", source_of_truth:"PD archive / Summer 2026", tags:["professional-learning"], last_activity_at:"2026-07-29", completed_at:"2026-07-29" },
  { ...base, id:"old-importer", title:"Legacy Enrollment CSV Macro", type:"Tool / App", area:"Technology", status:"Archived", priority:"Someday", impact:"Low", effort:"Quick", outcome:"Import legacy enrollment files.", next_action:"", source_of_truth:"Technology archive", tags:["enrollment","importer"], last_activity_at:"2025-11-12", completed_at:"2026-02-01", replaced_by:"Arts Import & Reconciliation" },
];

export const mockPromptResponses: Record<string, { title: string; body: string; proposal?: { itemId: string; field: "priority" | "status"; value: string } }> = {
  "What's worth working on today?": { title:"Today’s focus", body:"Finalize the Arts Intelligence Hub warning indicators, validate Enrollment Dashboard mappings, and unblock Valencia DirectConnect by defining its first concrete action. Together, these reduce near-term data risk and one visible planning gap." },
  "What am I forgetting in CTE?": { title:"CTE memory check", body:"Valencia DirectConnect Alignment is active but has no next action and has been quiet for 9 days. The outcome is defined; the immediate gap is ownership of the alignment conversation.", proposal:{ itemId:"valencia", field:"priority", value:"Now" } },
  "Show me stalled projects.": { title:"Stalled work", body:"Valencia DirectConnect has no next action. GenMusBot has had no activity in 13 days. FF&E Lessons Learned has been quiet for 11 days. No state has been changed." },
  "What have I already built around enrollment?": { title:"Enrollment ecosystem", body:"You already have a connected system: Enrollment Dashboard provides the trusted view; Arts Import & Reconciliation protects input quality; District Arts Intelligence Hub adds early warnings; Data Debrief Dashboard supports leadership conversations. A new importer likely overlaps with Arts Import & Reconciliation." },
  "Give me my weekly review.": { title:"Weekly review", body:"Progress: three enrollment-related items moved forward and two funding steps are complete. Waiting: Nova Lakes Stage Issue and Disney Musicals transportation. Review queue: Arts Import & Reconciliation, Modern Band Chart Builder, and Data Debrief Dashboard. One active item still needs a next action." },
};